apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-devops-lab-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-devops-lab-app
  template:
    metadata:
      labels:
        app: spring-devops-lab-app
    spec:
      containers:
        - name: spring-devops-lab-app
          image: spring-devops-lab:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: spring-devops-lab-config
            - secretRef:
                name: spring-devops-lab-secret
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15